<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NoWarn>CA1416</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../src/DiscRipper/Core/*.cs" Link="Core/%(Filename)%(Extension)" />
    <PackageReference Include="TagLibSharp" Version="2.3.0" />
    <PackageReference Include="System.IO.Hashing" Version="8.0.0" />
    <None Include="*.bin;*.txt;*.jpg;*.xml" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
